library(MetaboAnalystR)
source('functions.r')
mSet<-InitDataObjects("specbin", "stat", FALSE)
mSet<-Read.TextData(mSet, "script/data_processed.csv", "rowu", "disc");
mSet<-SanityCheckData(mSet)
mSet<-RemoveMissingPercent(mSet, percent=0.5)
mSet<-ImputeVar(mSet, method="min")
mSet<-FilterVariable(mSet, "iqr", "F", 25)
mSet<-PreparePrenormData(mSet)
mSet<-Normalization(mSet, "NULL", "NULL", "NULL", ratio=FALSE, ratioNum=20)
mSet<-PLSR.Anal(mSet, reg=TRUE)
mSet<-PlotPLS3DScoreImg(mSet, "pls_score3d_0_", "png", 72, width=NA, 1,2,3, 40)
mSet<-PLSDA.CV(mSet, "T",5, "Q2")
mSet<-SaveTransformedData(mSet)
mSet<-PlotPLS.Imp(mSet, "pls_imp_0_", "png", 72, width=NA, "vip", "Comp. 2", 15,FALSE)